import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import Sidebar from "../components/Sidebar";
import SideTab from "../components/SideTab";
import styles from "../styles/Home.module.css";

export default function Home({ exploreData, cardsData }) {
  return (
    // <div className={styles.container}>
    <div className="">
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex">
        <Sidebar />
        <div className="max-w-7xl mx-auto overflow-y-auto">
          <Banner />
        </div>
      </div>
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        {/* <LargeCard
          img="learning-img.png"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb."
          buttonText="Get Inspired"
        /> */}
      </main>
      <Footer />
    </div>
  );
}
