import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import MediumCard from "../components/MediumCard";

export default function Home() {
  const router = useRouter();
  const openCourses = () => {
    router.push({
      pathname: "/courses",
    });
  };
  return (
    <div className="">
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex">
        <Sidebar />
        <div className="max-w-7xl mx-auto overflow-y-auto">
          <Banner />
        </div>
      </div>
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <a className=" text-3xl lg:text-5xl font-semibold">
          Improve <span className="text-red-400">your skills faster</span>
        </a>
        <div className="flex justify-center align-middle pt-8">
          <img src="study-img.png" className=" w-[400px] md:w-[700px]"></img>
        </div>
        <a className="text-3xl lg:text-5xl font-semibold absolute lg:right-[100px]">
          Study with <span className="text-red-400">your own schedule</span>
        </a>
        <div className="flex justify-center pt-24 align-middle">
          <img src="stud2-img.png" className="w-[400px] md:w-[700px]"></img>
        </div>
        <div className="flex justify-center pt-10">
          <button
            className="bg-red-400 rounded-full text-white font-semibold px-6 py-2  text-2xl md:text-4xl shadow-md hover:shadow-lg active:scale-105 transform transition duration-200 ease-out"
            onClick={openCourses}
          >
            Go To Courses
          </button>
        </div>
        <div className="w-[300px] mx-auto lg:w-full">
          <MediumCard />
        </div>
      </main>
      <Footer />
    </div>
  );
}
